# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n com.tencent.client.common.protosB\nMWComProtoP\001\210\001\001'),
  serialized_pb=_b('\n\x0c\x63ommon.proto\"5\n\x0f\x43ompleteTaskReq\x12\x0e\n\x06taskId\x18\x01 \x01(\x03\x12\x12\n\ntimestamps\x18\x02 \x01(\x03\"\x19\n\x07VoidReq\x12\x0e\n\x06itemId\x18\x01 \x01(\x03\"\x17\n\x08VoidResp\x12\x0b\n\x03msg\x18\x01 \x01(\t*\'\n\nAsyncModel\x12\x07\n\x03\x42SP\x10\x00\x12\x07\n\x03SSP\x10\x01\x12\x07\n\x03\x41SP\x10\x02\x42\x33\n com.tencent.client.common.protosB\nMWComProtoP\x01\x88\x01\x01\x62\x06proto3')
)

_ASYNCMODEL = _descriptor.EnumDescriptor(
  name='AsyncModel',
  full_name='AsyncModel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BSP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SSP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASP', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=123,
  serialized_end=162,
)
_sym_db.RegisterEnumDescriptor(_ASYNCMODEL)

AsyncModel = enum_type_wrapper.EnumTypeWrapper(_ASYNCMODEL)
BSP = 0
SSP = 1
ASP = 2



_COMPLETETASKREQ = _descriptor.Descriptor(
  name='CompleteTaskReq',
  full_name='CompleteTaskReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='CompleteTaskReq.taskId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='CompleteTaskReq.timestamps', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=69,
)


_VOIDREQ = _descriptor.Descriptor(
  name='VoidReq',
  full_name='VoidReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemId', full_name='VoidReq.itemId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=96,
)


_VOIDRESP = _descriptor.Descriptor(
  name='VoidResp',
  full_name='VoidResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='VoidResp.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['CompleteTaskReq'] = _COMPLETETASKREQ
DESCRIPTOR.message_types_by_name['VoidReq'] = _VOIDREQ
DESCRIPTOR.message_types_by_name['VoidResp'] = _VOIDRESP
DESCRIPTOR.enum_types_by_name['AsyncModel'] = _ASYNCMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompleteTaskReq = _reflection.GeneratedProtocolMessageType('CompleteTaskReq', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETETASKREQ,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:CompleteTaskReq)
  })
_sym_db.RegisterMessage(CompleteTaskReq)

VoidReq = _reflection.GeneratedProtocolMessageType('VoidReq', (_message.Message,), {
  'DESCRIPTOR' : _VOIDREQ,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VoidReq)
  })
_sym_db.RegisterMessage(VoidReq)

VoidResp = _reflection.GeneratedProtocolMessageType('VoidResp', (_message.Message,), {
  'DESCRIPTOR' : _VOIDRESP,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:VoidResp)
  })
_sym_db.RegisterMessage(VoidResp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
